---
printWidth: 100
tabWidth: 4
useTabs: false
trailingComma: all
semi: true
singleQuote: false
overrides:
    - files: "**/*.md"
      options:
          tabWidth: 2
# plugins:
    # - node_modules/prettier-plugin-sort-class-names/prettier-plugin-sort-class-names.js
# - "./node_modules/@trivago/prettier-plugin-sort-imports/lib/src/index.js"

# sort-imports plugin
# importOrder:
#     - "^node:"
#     - "^[^@.]"
#     - "^@"
#     - "^\\."
# importOrderSortSpecifiers: true
