name: Temp File Sharing

on:
    workflow_dispatch:
        inputs:
            dir:
                description: The base directory to share
                required: false
                default: ".store"
            duration:
                description: The duration of the service to run. Number with optional suffix, 's' (default), 'm', 'h'.
                required: true
                default: "120m"

jobs:
    serve:
        runs-on: ubuntu-latest
        timeout-minutes: 1440 # maximum duration is 24 hours
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm build

            - name: Install Cloudflared
              run: |
                  curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
                  sudo dpkg -i cloudflared.deb

            - name: Start Tunnel (Anonymous)
              env:
                  TOKEN: ${{ secrets.TUNNEL_TOKEN }}
              if: ${{ env.TOKEN == '' }}
              run: |
                  sudo cloudflared tunnel --url http://localhost:3000 & sleep 5

            - name: Start Tunnel (Authenticated)
              env:
                  TOKEN: ${{ secrets.TUNNEL_TOKEN }}
              if: ${{ env.TOKEN != '' }}
              run: |
                  sudo cloudflared service install ${{ secrets.TUNNEL_TOKEN }} &

            - name: Start Server
              env:
                  DIR: ${{ inputs.dir }}
                  PERMISSIONS: ${{ secrets.PERMISSIONS }}
              run: |
                  date 
                  timeout ${{ github.event.inputs.duration }} pnpm run start || true
                  date
