name: Temp File Sharing

on:
    workflow_dispatch:

jobs:
    serve:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install
              run: npx -y pnpm i

            - name: Build
              run: npx -y pnpm build

            - name: Install Cloudflared
              run: brew install cloudflare/cloudflare/cloudflared

            - name: start server
              run: |
                  npx -y pnpm run start &
                  cloudflared tunnel --url http://localhost:3000
